// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvuqzjwhvcaidrzzrbqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2dXF6andodmNhaWRyenpyYnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDU2NDMsImV4cCI6MjA3Mzk4MTY0M30.lV55l-123yoRHyImT6c0w7lFdRpqOTyN6mVNgq36BPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});